Pipeline:
  Pods:
    - Name: ColorImageEntryPoint
      Type: EntryPoint<cv::Mat3b>
      Params: ~
      Inputs: ~
    - Name: DepthMatEntryPoint
      Type: EntryPoint<DepthMatConstPtr>
      Params: ~
      Inputs: ~
    - Name: MaskEntryPoint
      Type: EntryPoint<cv::Mat1b>
      Params: ~
      Inputs: ~
    - Name: SeedEntryPoint
      Type: EntryPoint<cv::Mat1b>
      Params: ~
      Inputs: ~
    - Name: DepthMatProjector
      Type: DepthMatProjector
      Params: ~
      Inputs:
        Image: ColorImageEntryPoint.Output
        DepthMat: DepthMatEntryPoint.Output
    - Name: OrganizedSurfaceNormalPod
      Type: OrganizedSurfaceNormalPod
      Params:
        Radius: 10
      Inputs:
        Mask: MaskEntryPoint.Output
        Cloud: DepthMatProjector.Cloud
    - Name: SeedNPG
      Type: SeedNPG
      Inputs:
        SeedImage: SeedEntryPoint.Output
        Image: ColorImageEntryPoint.Output
    - Name: EdgeStructureGenerator
      Type: EdgeStructureGenerator
      Params:
        Grid: True
        Diagonal: True
        Web: False
        WebMaxRadius: 3
        WebNumOutgoing: 3
      Inputs:
        Image: ColorImageEntryPoint.Output
        Mask: MaskEntryPoint.Output
    - Name: SimpleColorDifferenceEPG
      Type: SimpleColorDifferenceEPG
      Params:
        Sigma: 30
      Inputs:
        Image: ColorImageEntryPoint.Output
        EdgeStructure: EdgeStructureGenerator.EdgeStructure
    - Name: EdgePotentialAggregator
      Type: EdgePotentialAggregator
      Params: ~
      Inputs:
        Image: ColorImageEntryPoint.Output
        EdgeStructure: EdgeStructureGenerator.EdgeStructure
        UnweightedEdge: SimpleColorDifferenceEPG.Edge
    - Name: NodePotentialAggregator
      Type: NodePotentialAggregator
      Params: ~
      Inputs:
        Image: ColorImageEntryPoint.Output
        UnweightedNode: SeedNPG.Node